name: Pytester

on:
    push:
        branches: ["main"]
        pull_requests:
            branches: ["main"]
            workflow_dispach:
jobs:
    test:
        runs_on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up python
              uses: actions/setup-checkout@v3
              with:
                  python-version: "3.12.10"
                  cache: "pip"

            - name: Install dependencies
              run: |
                  python  -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: run integration tests
              run: |
                  python -m pytest -m integration_test
