name: Pytester

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Wait for mongo to be ready
              run: |
                  for i in {1..30}; do
                    mongosh --quiet --eval "db.adminCommand('ping')" && break
                    echo "Waiting for mongo..."
                    sleep 1
                  done

            - name: Set up python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
                  cache: "pip"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: run integration tests
              working-directory: ./backend
              run: |
                  python -m pytest -m integration_test
